### ISSUE TITLE
heroku deploy button to sup - https://devcenter.heroku.com/articles/heroku-button - https://devcenter.heroku.com/articles/app-json-schema

### ISSUE THREAD

**Issue by ilyakava** [ilyakava/sup#44]

**Comment by ilyakava** [comment]
This is the most important card in my opinion, any chance @Thrillberg or @4p00rv wants to take it on?

**Comment by 4p00rv** [comment]
I can take this on! Where should this card be visible? Github readme?

**Comment by ilyakava** [comment]
Thank you!

Yes the button should be at the top of the realm next to the other two waffle.io and travisci buttons.

**Comment by 4p00rv** [comment]
Please check pull request #68

**Comment by ilyakava** [comment]
I'm mass closing non-algo related issues as they are addressed [here](https://github.com/dblock/slack-sup).
