### ISSUE TITLE
Multiple member with same email address

### ISSUE THREAD

**Issue by 4p00rv** [ilyakava/sup#63]
I figured out that if you capitalize your already registered email than you can successfully register a new member but with same email.

**Comment by dblock** [comment]
Yep, it's a bug.

**Comment by 4p00rv** [comment]
I will push out a fix for this too!

**Comment by 4p00rv** [comment]
Resolved?

**Comment by bhoggard** [comment]
I had to manually delete a user, because `member.save!` would throw `Email has already been taken`. This has been deployed and the migration run. I don't have permission to close the bug.

**Comment by dblock** [comment]
@bhoggard Shouldn't have [the migration](https://github.com/ilyakava/sup/blob/master/db/migrate/20151127162510_downcase_email_and_remove_duplicate_entries.rb) take care of that?

I'll close this one.
